//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.10 at 11:33:27 AM CET 
//


package eu.sn.ecp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MessageState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VERIFYING"/>
 *     &lt;enumeration value="ACCEPTED"/>
 *     &lt;enumeration value="DELIVERING"/>
 *     &lt;enumeration value="DELIVERED"/>
 *     &lt;enumeration value="RECEIVED"/>
 *     &lt;enumeration value="FAILED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MessageState")
@XmlEnum
public enum MessageState {


    /**
     * The message is waiting for receiver verification due to connectivity problems between messaging component and Directory Service.
     * 
     */
    VERIFYING,

    /**
     * The message has been accepted by the ECP component and stored in the messagebox.
     * 
     */
    ACCEPTED,

    /**
     * The message has been successfully passed to another ECP component. At the moment, this ECP component has not yet obtained further information about message delivery into endpoint of the recipient.
     * 
     */
    DELIVERING,

    /**
     * The message has been delivered to the target endpoint.
     * 
     */
    DELIVERED,

    /**
     * The message has been received by target business application or user.
     * 
     */
    RECEIVED,

    /**
     * The processing of the message failed. 
     * 
     */
    FAILED;

    public String value() {
        return name();
    }

    public static MessageState fromValue(String v) {
        return valueOf(v);
    }

}
