//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.10 at 11:33:27 AM CET 
//


package eu.sn.ecp;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageTraceState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MessageTraceState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VERIFYING"/>
 *     &lt;enumeration value="ACCEPTED"/>
 *     &lt;enumeration value="TRANSPORTED"/>
 *     &lt;enumeration value="DELIVERED"/>
 *     &lt;enumeration value="RECEIVED"/>
 *     &lt;enumeration value="FAILED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MessageTraceState")
@XmlEnum
public enum MessageTraceState {

    VERIFYING,
    ACCEPTED,
    TRANSPORTED,
    DELIVERED,
    RECEIVED,
    FAILED;

    public String value() {
        return name();
    }

    public static MessageTraceState fromValue(String v) {
        return valueOf(v);
    }

}
