//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.10 at 11:33:27 AM CET 
//


package eu.sn.ecp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="receivedMessage" type="{http://ecp.entso-e.eu/}ReceivedMessage" minOccurs="0"/>
 *         &lt;element name="remainingMessagesCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "receivedMessage",
    "remainingMessagesCount"
})
@XmlRootElement(name = "ReceiveMessageResponse")
public class ReceiveMessageResponse {

    @XmlElementRef(name = "receivedMessage", type = JAXBElement.class)
    protected JAXBElement<ReceivedMessage> receivedMessage;
    protected long remainingMessagesCount;

    /**
     * Gets the value of the receivedMessage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ReceivedMessage }{@code >}
     *     
     */
    public JAXBElement<ReceivedMessage> getReceivedMessage() {
        return receivedMessage;
    }

    /**
     * Sets the value of the receivedMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ReceivedMessage }{@code >}
     *     
     */
    public void setReceivedMessage(JAXBElement<ReceivedMessage> value) {
        this.receivedMessage = ((JAXBElement<ReceivedMessage> ) value);
    }

    /**
     * Gets the value of the remainingMessagesCount property.
     * 
     */
    public long getRemainingMessagesCount() {
        return remainingMessagesCount;
    }

    /**
     * Sets the value of the remainingMessagesCount property.
     * 
     */
    public void setRemainingMessagesCount(long value) {
        this.remainingMessagesCount = value;
    }

}
