//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.10 at 11:33:27 AM CET 
//


package eu.sn.ecp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.Arrays;


/**
 * A representation of a message sent via SendMessage method
 * 
 * <p>Java class for SentMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SentMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="receiverCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="businessType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="senderApplication" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="baMessageID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SentMessage", propOrder = {
    "receiverCode",
    "businessType",
    "content",
    "senderApplication",
    "baMessageID"
})
public class SentMessage {

    @XmlElement(required = true)
    protected String receiverCode;
    @XmlElement(required = true)
    protected String businessType;
    @XmlElement(required = true)
    protected byte[] content;
    @XmlElementRef(name = "senderApplication", type = JAXBElement.class)
    protected JAXBElement<String> senderApplication;
    @XmlElementRef(name = "baMessageID", type = JAXBElement.class)
    protected JAXBElement<String> baMessageID;

    /**
     * Gets the value of the receiverCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiverCode() {
        return receiverCode;
    }

    /**
     * Sets the value of the receiverCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiverCode(String value) {
        this.receiverCode = value;
    }

    /**
     * Gets the value of the businessType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * Sets the value of the businessType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessType(String value) {
        this.businessType = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setContent(byte[] value) {
        this.content = ((byte[]) value);
    }

    /**
     * Gets the value of the senderApplication property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getSenderApplication() {
        return senderApplication;
    }

    /**
     * Sets the value of the senderApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setSenderApplication(JAXBElement<String> value) {
        this.senderApplication = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the baMessageID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBaMessageID() {
        return baMessageID;
    }

    /**
     * Sets the value of the baMessageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBaMessageID(JAXBElement<String> value) {
        this.baMessageID = ((JAXBElement<String> ) value);
    }


    @Override
    public String toString() {
        return "SentMessage{" +
                "receiverCode='" + receiverCode + '\'' +
                ", businessType='" + businessType + '\'' +
                ", content=" + Arrays.toString(content) +
                ", senderApplication=" + senderApplication +
                ", baMessageID=" + baMessageID +
                '}';
    }
}
